# Generated by Django 4.1.5 on 2023-02-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Latch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_id', models.CharField(max_length=11, unique=True)),
                ('urban_group', models.IntegerField(default=None, null=True)),
                ('est_vmiles', models.IntegerField(default=None, null=True)),
                ('hh_cnt', models.IntegerField(default=None, null=True)),
                ('vintage', models.CharField(default='2017', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='LifeExpectancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_id', models.CharField(max_length=11, unique=True)),
                ('value', models.FloatField(default=None, null=True)),
                ('vintage', models.CharField(default='2015', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MetricValence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=64)),
                ('valence', models.IntegerField(choices=[(1, 'positive'), (-1, 'negative')], default=1)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.community')),
            ],
        ),
    ]
