# Generated by Django 4.1.5 on 2023-02-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_id', models.CharField(max_length=11, unique=True)),
                ('D4c', models.FloatField(default=None, null=True)),
                ('vintage', models.CharField(default='2014', max_length=32)),
            ],
        ),
    ]
