# Generated by Django 4.1.5 on 2023-02-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0004_state_brfss'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=64)),
                ('percentile', models.IntegerField(default=None, null=True)),
                ('vintage', models.CharField(default='2019', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EducationCTSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=64)),
                ('subgroup', models.CharField(max_length=32)),
                ('ela_performance_index', models.FloatField(default=None, null=True)),
                ('math_performance_index', models.FloatField(default=None, null=True)),
                ('science_performance_index', models.FloatField(default=None, null=True)),
                ('vintage', models.CharField(default='2019', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EducationMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=64)),
                ('percentile', models.IntegerField(default=None, null=True)),
                ('vintage', models.CharField(default='2019', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EducationMASubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=64)),
                ('school', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=32)),
                ('percentile', models.IntegerField(default=None, null=True)),
                ('vintage', models.CharField(default='2019', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EducationRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=32)),
                ('star_rating', models.IntegerField(default=None, null=True)),
                ('vintage', models.CharField(default='2019', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='brfss',
            name='vintage',
            field=models.CharField(default='2018', max_length=32),
        ),
    ]
