# Generated by Django 4.1.5 on 2023-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0005_educationct_educationctsubgroup_educationma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationct',
            name='district',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='educationma',
            name='district',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='educationmasubgroup',
            name='district',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='educationmasubgroup',
            name='school',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='educationri',
            name='district',
            field=models.CharField(max_length=80),
        ),
    ]
