# Generated by Django 4.1.5 on 2023-02-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0006_alter_educationct_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationctsubgroup',
            name='subgroup',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='educationmasubgroup',
            name='group',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='educationri',
            name='group',
            field=models.CharField(max_length=80),
        ),
    ]
