# Generated by Django 4.1.5 on 2023-02-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0007_alter_educationctsubgroup_subgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationctsubgroup',
            name='district',
            field=models.CharField(max_length=80),
        ),
    ]
