# Generated by Django 4.1.5 on 2023-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0013_alter_metric_unique_together_dataset_unique dataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeexpectancy',
            name='standard_error',
            field=models.FloatField(default=None, null=True),
        ),
    ]
