# Generated by Django 4.1.5 on 2023-02-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0014_lifeexpectancy_standard_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latch',
            name='est_vmiles',
            field=models.FloatField(default=None, null=True),
        ),
    ]
