# Generated by Django 4.1.7 on 2023-03-24 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthscore', '0015_alter_latch_est_vmiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Healthscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('title', models.CharField(default='New score', max_length=100)),
                ('address', models.CharField(max_length=80)),
                ('county_code', models.CharField(max_length=4)),
                ('county_name', models.CharField(max_length=80)),
                ('block_group', models.CharField(max_length=1)),
                ('school_district', models.CharField(max_length=80)),
                ('buffer_radius', models.IntegerField(default=None)),
                ('population_threshold', models.FloatField(default=None)),
                ('all_tracts', models.ManyToManyField(related_name='healthscores', to='healthscore.censustract')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.community')),
                ('primary_tract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.censustract')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
