# Generated by Django 4.1.7 on 2023-03-28 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0016_censustract_healthscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthscore',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
