# Generated by Django 4.1.7 on 2023-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0017_alter_healthscore_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_id', models.CharField(max_length=16, unique=True)),
                ('district_name', models.CharField(max_length=80)),
            ],
        ),
    ]
