# Generated by Django 4.1.7 on 2023-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0018_schooldistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldistrict',
            name='vintage',
            field=models.CharField(default='2022', max_length=32),
        ),
        migrations.AlterField(
            model_name='schooldistrict',
            name='tract_id',
            field=models.CharField(max_length=16),
        ),
    ]
