# Generated by Django 4.1.7 on 2023-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0019_schooldistrict_vintage_alter_schooldistrict_tract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationct',
            name='percentile',
            field=models.FloatField(default=None, null=True),
        ),
    ]
