# Generated by Django 4.1.7 on 2023-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0020_alter_educationct_percentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NMTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_id', models.CharField(max_length=16)),
                ('eligible', models.BooleanField()),
            ],
        ),
    ]
