# Generated by Django 4.1.7 on 2023-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0021_nmtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmtc',
            name='vintage',
            field=models.CharField(default='2015', max_length=32),
        ),
    ]
