# Generated by Django 4.1.7 on 2023-06-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0022_nmtc_vintage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthscore',
            name='buffer_radius',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='population_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='HousingUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=128)),
                ('unit_count', models.IntegerField()),
                ('starting_rent', models.IntegerField()),
                ('healthscore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.healthscore')),
            ],
        ),
    ]
