# Generated by Django 4.1.7 on 2023-06-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0023_alter_healthscore_buffer_radius_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='tract_id',
            new_name='geoid',
        ),
    ]
