# Generated by Django 4.1.7 on 2023-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0028_alter_dataset_vintage_latchbystate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatchByState',
            new_name='NHTS',
        ),
    ]
