# Generated by Django 4.1.7 on 2023-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0029_rename_latchbystate_nhts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhts',
            old_name='est_vmiles',
            new_name='est_vmiles_rural',
        ),
        migrations.RemoveField(
            model_name='nhts',
            name='urban_group',
        ),
        migrations.AddField(
            model_name='nhts',
            name='est_vmiles_suburban',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='nhts',
            name='est_vmiles_urban',
            field=models.FloatField(default=None, null=True),
        ),
    ]
