# Generated by Django 4.1.7 on 2023-09-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0032_remove_datasource_descriptor_dataset_descriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brfss',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='educationct',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='educationctsubgroup',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='educationma',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='educationmasubgroup',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='educationri',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='latch',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='lifeexpectancy',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='nmtc',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='opportunityzone',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='schooldistrict',
            name='vintage',
        ),
        migrations.RemoveField(
            model_name='smartlocation',
            name='vintage',
        ),
    ]
