# Generated by Django 4.1.7 on 2023-12-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0034_healthscore_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=64, null=True)),
                ('value', models.FloatField(default=None, null=True)),
                ('moe', models.FloatField(default=None, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.dataset')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthscore.state')),
            ],
        ),
    ]
