# Generated by Django 4.1.7 on 2023-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0035_childmortality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmortality',
            name='state',
        ),
        migrations.AddField(
            model_name='childmortality',
            name='state_fips',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
