# Generated by Django 4.1.7 on 2023-12-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0036_remove_childmortality_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmortality',
            name='county',
        ),
        migrations.AddField(
            model_name='childmortality',
            name='county_fips',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
