# Generated by Django 4.1.7 on 2023-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0037_remove_childmortality_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmortality',
            name='state_fips',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
