# Generated by Django 4.1.7 on 2023-12-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0039_personalhealthcare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_fips', models.CharField(max_length=2, null=True)),
                ('value', models.IntegerField(default=None, null=True)),
                ('moe', models.FloatField(default=None, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.dataset')),
            ],
        ),
    ]
