# Generated by Django 4.1.7 on 2023-12-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0040_childhealth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childhealth',
            old_name='moe',
            new_name='asthma_moe',
        ),
        migrations.RemoveField(
            model_name='childhealth',
            name='value',
        ),
        migrations.AddField(
            model_name='childhealth',
            name='asthma_value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='childhealth',
            name='obesity_moe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='childhealth',
            name='obesity_value',
            field=models.FloatField(default=None, null=True),
        ),
    ]
