# Generated by Django 4.1.7 on 2024-01-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0041_rename_moe_childhealth_asthma_moe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_fips', models.CharField(max_length=2, null=True)),
                ('state_local_value', models.IntegerField(default=None, null=True)),
                ('non_profit_value', models.IntegerField(default=None, null=True)),
                ('for_profit_value', models.IntegerField(default=None, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.dataset')),
            ],
        ),
    ]
