# Generated by Django 4.1.7 on 2024-01-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0042_ervisits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_fips', models.CharField(max_length=5)),
                ('county_name', models.CharField(max_length=80)),
                ('care_level', models.CharField(max_length=32)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.dataset')),
            ],
        ),
    ]
