# Generated by Django 4.1.7 on 2024-01-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0043_maternitycare'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_fips', models.CharField(max_length=2, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.dataset')),
            ],
        ),
    ]
