# Generated by Django 4.1.7 on 2024-02-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0044_mentalhealthcare'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdBurden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(max_length=16)),
                ('transportation_value', models.FloatField(default=None, null=True)),
                ('energy_value', models.FloatField(default=None, null=True)),
                ('transportation_burden', models.CharField(max_length=6)),
                ('energy_burden', models.CharField(max_length=6)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthscore.dataset')),
            ],
        ),
    ]
