# Generated by Django 4.1.7 on 2024-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0045_householdburden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdburden',
            name='energy_burden',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='householdburden',
            name='transportation_burden',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
