# Generated by Django 4.1.7 on 2024-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0047_homelessness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartlocation',
            name='block_group_id',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddIndex(
            model_name='smartlocation',
            index=models.Index(fields=['dataset'], name='healthscore_dataset_c25fd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='smartlocation',
            constraint=models.UniqueConstraint(fields=('dataset', 'block_group_id'), name='unique block group'),
        ),
    ]
