# Generated by Django 4.1.7 on 2024-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthscore', '0048_alter_smartlocation_block_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmortality',
            name='county_fips',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddIndex(
            model_name='childmortality',
            index=models.Index(fields=['dataset'], name='healthscore_dataset_da4fa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='childmortality',
            constraint=models.UniqueConstraint(fields=('dataset', 'county_fips'), name='unique mortality record'),
        ),
    ]
